apiVersion: v1
kind: Secret
metadata:
  name: upvshop-secrets
type: Opaque
stringData:
  database-url: "postgresql://admin:secret123@db:5432/upvshop"
  jwt-secret: "upvshop-super-secret-jwt-key-2024"
  db-user: "admin"
  db-password: "secret123"
